export const notionSnapshot = {
  "capturedAt": "2026-08-31",
  "sourceCounts": {
    "accounts": 10,
    "projects": 63,
    "tasks": 320,
    "team": 20,
    "holidays": 73,
    "ratedTasks": 149,
    "ratedProjects": 35,
    "evaluations": 0,
    "activeProjects": 23,
    "activeTasks": 61,
    "upcomingAbsences": 3
  },
  "dataQuality": {
    "missingTaskEffort": 320,
    "missingProjectComplexity": 63,
    "missingTaskPeople": 25,
    "missingProjectPeople": 17,
    "missingTaskDates": 13,
    "missingEvaluationAuthor": 0,
    "missingEvaluationComment": 0,
    "teamMissingSkills": 2,
    "teamMissingGrowth": 10,
    "teamMissingJoined": 2
  },
  "accounts": [
    {
      "name": "Iberdrola",
      "priority": "Alta",
      "contract": "Fee",
      "color": "#8fe94f",
      "projects": 4,
      "tasks": 8,
      "activity": 53,
      "url": "https://app.notion.com/p/2b94f145f5cf8094950ee867dea9f6e7"
    },
    {
      "name": "ONCE",
      "priority": "Alta",
      "contract": "Fee",
      "color": "#f97382",
      "projects": 4,
      "tasks": 26,
      "activity": 100,
      "url": "https://app.notion.com/p/2b94f145f5cf80fd9804f7f9c4999951"
    },
    {
      "name": "Leroy Merlin",
      "priority": "Alta",
      "contract": "Fee",
      "color": "#52c988",
      "projects": 4,
      "tasks": 7,
      "activity": 50,
      "url": "https://app.notion.com/p/2b94f145f5cf80dcafafd0efd1de30a0"
    },
    {
      "name": "Banca March",
      "priority": "Media",
      "contract": "Fee",
      "color": "#f2ca52",
      "projects": 2,
      "tasks": 1,
      "activity": 18,
      "url": "https://app.notion.com/p/2b94f145f5cf8039b079daaf70888bb6"
    },
    {
      "name": "ING",
      "priority": "Baja",
      "contract": "Proyecto",
      "color": "#ff8d43",
      "projects": 3,
      "tasks": 3,
      "activity": 32,
      "url": "https://app.notion.com/p/2b94f145f5cf80fab84dcc592274efd6"
    },
    {
      "name": "Carmen",
      "priority": "Baja",
      "contract": "NNBB",
      "color": "#ac8cff",
      "projects": 3,
      "tasks": 9,
      "activity": 47,
      "url": "https://app.notion.com/p/2b94f145f5cf8078bf27e3f6ed1df1df"
    },
    {
      "name": "Ogilvy",
      "priority": "Baja",
      "contract": "Otro",
      "color": "#7e8b86",
      "projects": 1,
      "tasks": 6,
      "activity": 24,
      "url": "https://app.notion.com/p/2b94f145f5cf800fa553f34ee1ef31b0"
    }
  ],
  "projects": [
    {
      "id": "35e4f145f5cf80a7b09cf3daad068217",
      "name": "11 del 11 / 26",
      "status": "Pre-Producción",
      "account": "ONCE",
      "timing": "12 MAY — 11 NOV",
      "type": "Proyecto",
      "people": [],
      "priority": "Media",
      "url": "https://app.notion.com/p/35e4f145f5cf80a7b09cf3daad068217",
      "rating": null,
      "complexity": null
    },
    {
      "id": "3444f145f5cf808a9425dcea4dadf8c1",
      "name": "Extra Navidad",
      "status": "Pre-Producción",
      "account": "ONCE",
      "timing": "16 ABR — 31 DIC",
      "type": "Campaña",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/3444f145f5cf808a9425dcea4dadf8c1",
      "rating": null,
      "complexity": null
    },
    {
      "id": "3b44f145f5cf81b2b076f769733741c5",
      "name": "Mundial Femenino",
      "status": "Ideas",
      "account": "Iberdrola",
      "timing": "SIN FECHA",
      "type": "Proyecto",
      "people": [],
      "priority": "Sin prioridad",
      "url": "https://app.notion.com/p/3b44f145f5cf81b2b076f769733741c5",
      "rating": null,
      "complexity": null
    },
    {
      "id": "3bf4f145f5cf8099ad19e954817244b9",
      "name": "Ferrero 2026",
      "status": "Brief",
      "account": "Banca March",
      "timing": "16 AGO — 17 SEP",
      "type": "Proyecto",
      "people": [],
      "priority": "Sin prioridad",
      "url": "https://app.notion.com/p/3bf4f145f5cf8099ad19e954817244b9",
      "rating": null,
      "complexity": null
    },
    {
      "id": "3b54f145f5cf804cb59fd935315f20a8",
      "name": "Proyectos II",
      "status": "Brief",
      "account": "Leroy Merlin",
      "timing": "24 AGO — 30 SEP",
      "type": "Campaña",
      "people": [],
      "priority": "Sin prioridad",
      "url": "https://app.notion.com/p/3b54f145f5cf804cb59fd935315f20a8",
      "rating": null,
      "complexity": null
    },
    {
      "id": "3b54f145f5cf803d8e53fc920e236604",
      "name": "Decoracion",
      "status": "Brief",
      "account": "Leroy Merlin",
      "timing": "01 SEP",
      "type": "Campaña",
      "people": [],
      "priority": "Sin prioridad",
      "url": "https://app.notion.com/p/3b54f145f5cf803d8e53fc920e236604",
      "rating": null,
      "complexity": null
    },
    {
      "id": "35e4f145f5cf807ca5cffe82e3af21ba",
      "name": "Rasca Familia Millonario",
      "status": "Seguimiento",
      "account": "ONCE",
      "timing": "10 MAY — 21 SEP",
      "type": "Proyecto",
      "people": [],
      "priority": "Sin prioridad",
      "url": "https://app.notion.com/p/35e4f145f5cf807ca5cffe82e3af21ba",
      "rating": 3,
      "complexity": null
    },
    {
      "id": "3504f145f5cf809a9d3efbdafc2f6740",
      "name": "Cuota Fija",
      "status": "Seguimiento",
      "account": "Iberdrola",
      "timing": "29 ABR — 15 SEP",
      "type": "Pitch",
      "people": [],
      "priority": "Media",
      "url": "https://app.notion.com/p/3504f145f5cf809a9d3efbdafc2f6740",
      "rating": 3,
      "complexity": null
    },
    {
      "id": "3264f145f5cf80b89390f17352809a66",
      "name": "GFDLC 26",
      "status": "Seguimiento",
      "account": "Leroy Merlin",
      "timing": "08 ABR — 31 JUL",
      "type": "Campaña",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/3264f145f5cf80b89390f17352809a66",
      "rating": 3,
      "complexity": null
    },
    {
      "id": "31e4f145f5cf80ea9ad4dcabfaf87001",
      "name": "Aniversario Oficinas",
      "status": "Seguimiento",
      "account": "ING",
      "timing": "09 MAR — 31 JUL",
      "type": "Proyecto",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/31e4f145f5cf80ea9ad4dcabfaf87001",
      "rating": null,
      "complexity": null
    },
    {
      "id": "2bc4f145f5cf806c9bcfcd38df2af1f5",
      "name": "Publicidad",
      "status": "Daily",
      "account": "Iberdrola",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2bc4f145f5cf806c9bcfcd38df2af1f5",
      "rating": 1,
      "complexity": null
    },
    {
      "id": "2bc4f145f5cf80a19647e7c6ef4b441a",
      "name": "Daily BM",
      "status": "Daily",
      "account": "Banca March",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2bc4f145f5cf80a19647e7c6ef4b441a",
      "rating": 1,
      "complexity": null
    },
    {
      "id": "2f04f145f5cf80e189acc2179bc3a22b",
      "name": "Supera",
      "status": "Daily",
      "account": "Iberdrola",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2f04f145f5cf80e189acc2179bc3a22b",
      "rating": 2,
      "complexity": null
    },
    {
      "id": "2bc4f145f5cf8093b566ddf4b9ede8d0",
      "name": "Daily ING",
      "status": "Daily",
      "account": "ING",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2bc4f145f5cf8093b566ddf4b9ede8d0",
      "rating": 1,
      "complexity": null
    },
    {
      "id": "2bd4f145f5cf806e8bd0fa176c3ad1f8",
      "name": "Daily Carmen",
      "status": "Daily",
      "account": "Carmen",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2bd4f145f5cf806e8bd0fa176c3ad1f8",
      "rating": 2,
      "complexity": null
    },
    {
      "id": "2e24f145f5cf80f4b787db1c5db25030",
      "name": "Daily ONCE",
      "status": "Daily",
      "account": "ONCE",
      "timing": "SIN FECHA",
      "type": "Daily",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2e24f145f5cf80f4b787db1c5db25030",
      "rating": 2,
      "complexity": null
    },
    {
      "id": "2b94f145f5cf80948d98db135abec202",
      "name": "Vitruvio & Atenea",
      "status": "Standby",
      "account": "Carmen",
      "timing": "SIN FECHA",
      "type": "Proactive",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2b94f145f5cf80948d98db135abec202",
      "rating": 5,
      "complexity": null
    },
    {
      "id": "2c44f145f5cf8056bd91cd7ff0278cf7",
      "name": "Dove",
      "status": "Parado",
      "account": "Ogilvy",
      "timing": "SIN FECHA",
      "type": "Proactive",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2c44f145f5cf8056bd91cd7ff0278cf7",
      "rating": 5,
      "complexity": null
    },
    {
      "id": "2b94f145f5cf8032a157d7d7b5ed92fe",
      "name": "Danacol",
      "status": "Parado",
      "account": "Carmen",
      "timing": "08 MAY — 02 JUN",
      "type": "Proactive",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2b94f145f5cf8032a157d7d7b5ed92fe",
      "rating": null,
      "complexity": null
    },
    {
      "id": "2b94f145f5cf804b823bce04e3ad69d7",
      "name": "Pitch 2026",
      "status": "Parado",
      "account": "Ruavieja",
      "timing": "SIN FECHA",
      "type": "Proyecto",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2b94f145f5cf804b823bce04e3ad69d7",
      "rating": null,
      "complexity": null
    },
    {
      "id": "2b94f145f5cf8039b0f9cadfa790eba5",
      "name": "Estopa",
      "status": "Parado",
      "account": "Ruavieja",
      "timing": "SIN FECHA",
      "type": "Proyecto",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2b94f145f5cf8039b0f9cadfa790eba5",
      "rating": 3,
      "complexity": null
    },
    {
      "id": "3574f145f5cf803796d3c5bf53d74a0e",
      "name": "Navidad LM",
      "status": "Parado",
      "account": "Leroy Merlin",
      "timing": "04 MAY — 31 MAY",
      "type": "Proyecto",
      "people": [],
      "priority": "Media",
      "url": "https://app.notion.com/p/3574f145f5cf803796d3c5bf53d74a0e",
      "rating": null,
      "complexity": null
    },
    {
      "id": "2d14f145f5cf806a8fbcfd8fac0b61d8",
      "name": "Flagship",
      "status": "Parado",
      "account": "ING",
      "timing": "01 ENE — 22 ENE",
      "type": "Proyecto",
      "people": [],
      "priority": "Baja",
      "url": "https://app.notion.com/p/2d14f145f5cf806a8fbcfd8fac0b61d8",
      "rating": null,
      "complexity": null
    }
  ],
  "tasks": [
    {
      "id": "2e94f145f5cf80859d35fce0cf870dde",
      "name": "Panelización",
      "status": "En progreso",
      "priority": "Alta",
      "project": "Transversal",
      "account": "ONCE",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2e94f145f5cf80859d35fce0cf870dde",
      "rating": null,
      "effort": null
    },
    {
      "id": "2be4f145f5cf8081b983f1b05d736c44",
      "name": "Briefing",
      "status": "Pausa",
      "priority": "Alta",
      "project": "Pitch 2026",
      "account": "Ruavieja",
      "date": "31 ENE",
      "people": [],
      "url": "https://app.notion.com/p/2be4f145f5cf8081b983f1b05d736c44",
      "rating": null,
      "effort": null
    },
    {
      "id": "3c64f145f5cf80edb2e1c5f7afb538ba",
      "name": "Presentacion",
      "status": "En progreso",
      "priority": "Alta",
      "project": "Mundial Femenino",
      "account": "Iberdrola",
      "date": "10 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3c64f145f5cf80edb2e1c5f7afb538ba",
      "rating": null,
      "effort": null
    },
    {
      "id": "3b84f145f5cf8112b557c0d540877dc0",
      "name": "Ideas",
      "status": "En progreso",
      "priority": "Alta",
      "project": "Mundial Femenino",
      "account": "Iberdrola",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/3b84f145f5cf8112b557c0d540877dc0",
      "rating": 4,
      "effort": null
    },
    {
      "id": "3914f145f5cf80e7a8bee8cff0a31767",
      "name": "PPM",
      "status": "En progreso",
      "priority": "Alta",
      "project": "Cuota Fija",
      "account": "Iberdrola",
      "date": "10 JUL",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80e7a8bee8cff0a31767",
      "rating": null,
      "effort": null
    },
    {
      "id": "3114f145f5cf80e0ab16e42ca675e461",
      "name": "Maqueta Encuentro",
      "status": "En progreso",
      "priority": "Alta",
      "project": "Transversal",
      "account": "ONCE",
      "date": "27 FEB",
      "people": [],
      "url": "https://app.notion.com/p/3114f145f5cf80e0ab16e42ca675e461",
      "rating": null,
      "effort": null
    },
    {
      "id": "3104f145f5cf8019a84bfac90a69e478",
      "name": "Status Equipo",
      "status": "Pendiente",
      "priority": "Alta",
      "project": "Sin proyecto",
      "account": "Ogilvy",
      "date": "09 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3104f145f5cf8019a84bfac90a69e478",
      "rating": null,
      "effort": null
    },
    {
      "id": "2ed4f145f5cf80a19122fc0cd0d18f18",
      "name": "Flagship Pitch",
      "status": "Pausa",
      "priority": "Alta",
      "project": "Flagship",
      "account": "ING",
      "date": "22 ENE",
      "people": [],
      "url": "https://app.notion.com/p/2ed4f145f5cf80a19122fc0cd0d18f18",
      "rating": null,
      "effort": null
    },
    {
      "id": "2ed4f145f5cf80d7b39ff4f55fdf5caf",
      "name": "Check Flasgship",
      "status": "Pausa",
      "priority": "Alta",
      "project": "Flagship",
      "account": "ING",
      "date": "21 ENE",
      "people": [],
      "url": "https://app.notion.com/p/2ed4f145f5cf80d7b39ff4f55fdf5caf",
      "rating": null,
      "effort": null
    },
    {
      "id": "2bc4f145f5cf80a08861cbb5e8855aa8",
      "name": "Briefing Danacol",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Danacol",
      "account": "Carmen",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2bc4f145f5cf80a08861cbb5e8855aa8",
      "rating": 4,
      "effort": null
    },
    {
      "id": "3914f145f5cf80089540fafe7cdd3e29",
      "name": "Offline CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Extra Navidad",
      "account": "ONCE",
      "date": "15 OCT",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80089540fafe7cdd3e29",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf800bb681ff2b42d139ad",
      "name": "Offline AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Extra Navidad",
      "account": "ONCE",
      "date": "13 OCT",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf800bb681ff2b42d139ad",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80a4bfadc385e42cf211",
      "name": "Rodaje",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Extra Navidad",
      "account": "ONCE",
      "date": "07 OCT",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80a4bfadc385e42cf211",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80e3aeb9caa3e3c99074",
      "name": "PPM CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Extra Navidad",
      "account": "ONCE",
      "date": "05 OCT",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80e3aeb9caa3e3c99074",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80f1a9f2c4155bb22b83",
      "name": "PPM AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Extra Navidad",
      "account": "ONCE",
      "date": "02 OCT",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80f1a9f2c4155bb22b83",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80e3a674fd3b66c59ff4",
      "name": "Offline CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "30 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80e3a674fd3b66c59ff4",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80379340e990e83b4429",
      "name": "Offline AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "29 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80379340e990e83b4429",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80c8901efaffebc066e8",
      "name": "Rodaje",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "24 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80c8901efaffebc066e8",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf807dba0ec944c5d5164a",
      "name": "PPM CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "21 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf807dba0ec944c5d5164a",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80559871ee7f77893753",
      "name": "PPM AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "18 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80559871ee7f77893753",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf803da544e416f4f52714",
      "name": "Subida Copias",
      "status": "En progreso",
      "priority": "Media",
      "project": "Rasca Familia Millonario",
      "account": "ONCE",
      "date": "16 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf803da544e416f4f52714",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80aea119c199d762df11",
      "name": "Offline CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Rasca Familia Millonario",
      "account": "ONCE",
      "date": "04 AGO",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80aea119c199d762df11",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80768bffc07ffc4ba409",
      "name": "Offline AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Rasca Familia Millonario",
      "account": "ONCE",
      "date": "03 AGO",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80768bffc07ffc4ba409",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf80dcafb6e5468b0defa0",
      "name": "Rodaje",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Rasca Familia Millonario",
      "account": "ONCE",
      "date": "30 JUL",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf80dcafb6e5468b0defa0",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf801bb352d6cacc3edfb6",
      "name": "TRATAMIENTO CL",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "29 JUL",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf801bb352d6cacc3edfb6",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf8072b2dbe4f659f6da0b",
      "name": "TRATAMIENTO AG",
      "status": "Pendiente",
      "priority": "Media",
      "project": "11 del 11 / 26",
      "account": "ONCE",
      "date": "28 JUL",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf8072b2dbe4f659f6da0b",
      "rating": null,
      "effort": null
    },
    {
      "id": "35d4f145f5cf8042b25dc49c232b5269",
      "name": "Presentacion",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Navidad LM",
      "account": "Leroy Merlin",
      "date": "13 MAY",
      "people": [],
      "url": "https://app.notion.com/p/35d4f145f5cf8042b25dc49c232b5269",
      "rating": null,
      "effort": null
    },
    {
      "id": "3564f145f5cf806990f2e48cf49b6095",
      "name": "Presentacion Ideas",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Cuota Fija",
      "account": "Iberdrola",
      "date": "14 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3564f145f5cf806990f2e48cf49b6095",
      "rating": null,
      "effort": null
    },
    {
      "id": "3434f145f5cf80babef9da6770c6c2e4",
      "name": "ONLINE",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Transversal",
      "account": "ONCE",
      "date": "13 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3434f145f5cf80babef9da6770c6c2e4",
      "rating": 3,
      "effort": null
    },
    {
      "id": "3434f145f5cf80f99c44fcbfe0150bcb",
      "name": "Color",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Transversal",
      "account": "ONCE",
      "date": "12 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3434f145f5cf80f99c44fcbfe0150bcb",
      "rating": 3,
      "effort": null
    },
    {
      "id": "30c4f145f5cf8003a645fbd1b49f0ee9",
      "name": "Contrario",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Direccion Creativa",
      "account": "Ogilvy",
      "date": "05 MAR",
      "people": [],
      "url": "https://app.notion.com/p/30c4f145f5cf8003a645fbd1b49f0ee9",
      "rating": null,
      "effort": null
    },
    {
      "id": "2d14f145f5cf8030b41fccd926a37dd0",
      "name": "Briefing Oficina",
      "status": "Pendiente",
      "priority": "Media",
      "project": "Flagship",
      "account": "ING",
      "date": "22 DIC",
      "people": [],
      "url": "https://app.notion.com/p/2d14f145f5cf8030b41fccd926a37dd0",
      "rating": 2,
      "effort": null
    },
    {
      "id": "2bc4f145f5cf80d19509e6d92f41616e",
      "name": "Presentacion",
      "status": "Pausa",
      "priority": "Baja",
      "project": "Vitruvio & Atenea",
      "account": "Carmen",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2bc4f145f5cf80d19509e6d92f41616e",
      "rating": null,
      "effort": null
    },
    {
      "id": "2bc4f145f5cf80fda7dde6610ac364ac",
      "name": "Presentacion Ideas",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Vitruvio & Atenea",
      "account": "Carmen",
      "date": "12 DIC",
      "people": [],
      "url": "https://app.notion.com/p/2bc4f145f5cf80fda7dde6610ac364ac",
      "rating": 4,
      "effort": null
    },
    {
      "id": "2bc4f145f5cf8031ac09ca86b5a8ecc3",
      "name": "MK Operativo",
      "status": "En progreso",
      "priority": "Baja",
      "project": "Publicidad",
      "account": "Iberdrola",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2bc4f145f5cf8031ac09ca86b5a8ecc3",
      "rating": 1,
      "effort": null
    },
    {
      "id": "2bc4f145f5cf80788e71e52d51a3309d",
      "name": "Mi Iberdrola",
      "status": "En progreso",
      "priority": "Baja",
      "project": "Publicidad",
      "account": "Iberdrola",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2bc4f145f5cf80788e71e52d51a3309d",
      "rating": 3,
      "effort": null
    },
    {
      "id": "2e74f145f5cf8039a3d5e519824df183",
      "name": "Supers Eurojackpot",
      "status": "En progreso",
      "priority": "Baja",
      "project": "Eurojackpot",
      "account": "ONCE",
      "date": "15 ENE",
      "people": [],
      "url": "https://app.notion.com/p/2e74f145f5cf8039a3d5e519824df183",
      "rating": null,
      "effort": null
    },
    {
      "id": "3c64f145f5cf8013a38add7b1fe64a52",
      "name": "Sonorizacion",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Rasca Familia Millonario",
      "account": "ONCE",
      "date": "26 AGO",
      "people": [],
      "url": "https://app.notion.com/p/3c64f145f5cf8013a38add7b1fe64a52",
      "rating": null,
      "effort": null
    },
    {
      "id": "3724f145f5cf80598e90c60cfe74a949",
      "name": "Estatus (6)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "26 JUN",
      "people": [],
      "url": "https://app.notion.com/p/3724f145f5cf80598e90c60cfe74a949",
      "rating": null,
      "effort": null
    },
    {
      "id": "3724f145f5cf80d7b0efc02fa02116db",
      "name": "Estatus (5)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "19 JUN",
      "people": [],
      "url": "https://app.notion.com/p/3724f145f5cf80d7b0efc02fa02116db",
      "rating": null,
      "effort": null
    },
    {
      "id": "35a4f145f5cf804b82f0f469b57158c8",
      "name": "Estatus (4)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "12 JUN",
      "people": [],
      "url": "https://app.notion.com/p/35a4f145f5cf804b82f0f469b57158c8",
      "rating": null,
      "effort": null
    },
    {
      "id": "35a4f145f5cf80ceacecfc29990872c6",
      "name": "Estatus (3)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "05 JUN",
      "people": [],
      "url": "https://app.notion.com/p/35a4f145f5cf80ceacecfc29990872c6",
      "rating": null,
      "effort": null
    },
    {
      "id": "35a4f145f5cf8057a05cd285d77c959f",
      "name": "Estatus (2)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "29 MAY",
      "people": [],
      "url": "https://app.notion.com/p/35a4f145f5cf8057a05cd285d77c959f",
      "rating": null,
      "effort": null
    },
    {
      "id": "35a4f145f5cf80058806cb4268b93e4e",
      "name": "Estatus (1)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Danacol",
      "account": "Carmen",
      "date": "22 MAY",
      "people": [],
      "url": "https://app.notion.com/p/35a4f145f5cf80058806cb4268b93e4e",
      "rating": null,
      "effort": null
    },
    {
      "id": "3584f145f5cf80d3a4eee4820da0e252",
      "name": "Pre PPM",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Proyectos II",
      "account": "Leroy Merlin",
      "date": "13 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3584f145f5cf80d3a4eee4820da0e252",
      "rating": null,
      "effort": null
    },
    {
      "id": "3574f145f5cf806ba80ec06a390f62c0",
      "name": "PPM",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Proyectos II",
      "account": "Leroy Merlin",
      "date": "14 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3574f145f5cf806ba80ec06a390f62c0",
      "rating": null,
      "effort": null
    },
    {
      "id": "3524f145f5cf80e0b944e403049ebd33",
      "name": "Entrega Maquetas",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Cuota Fija",
      "account": "Iberdrola",
      "date": "25 MAY",
      "people": [],
      "url": "https://app.notion.com/p/3524f145f5cf80e0b944e403049ebd33",
      "rating": null,
      "effort": null
    },
    {
      "id": "32e4f145f5cf80b79f0feb6d276ab335",
      "name": "Check Ideas",
      "status": "En progreso",
      "priority": "Baja",
      "project": "GFDLC 26",
      "account": "Leroy Merlin",
      "date": "25 MAR",
      "people": [],
      "url": "https://app.notion.com/p/32e4f145f5cf80b79f0feb6d276ab335",
      "rating": null,
      "effort": null
    },
    {
      "id": "3174f145f5cf801d9b9ff8b1717cb1c2",
      "name": "Brief LM Verano",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Verano Leroy 26",
      "account": "Leroy Merlin",
      "date": "04 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3174f145f5cf801d9b9ff8b1717cb1c2",
      "rating": null,
      "effort": null
    },
    {
      "id": "3174f145f5cf80eab5e5eb33199fa214",
      "name": "Check Cuentas",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Transversal",
      "account": "ONCE",
      "date": "03 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3174f145f5cf80eab5e5eb33199fa214",
      "rating": null,
      "effort": null
    },
    {
      "id": "30c4f145f5cf80e3b2b5fa7f7ad7072d",
      "name": "Ideas Cuentas",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Verano ONCE 26",
      "account": "ONCE",
      "date": "20 FEB",
      "people": [],
      "url": "https://app.notion.com/p/30c4f145f5cf80e3b2b5fa7f7ad7072d",
      "rating": 3,
      "effort": null
    },
    {
      "id": "30a4f145f5cf80ca990cd44aa774cd06",
      "name": "Offline iA",
      "status": "En progreso",
      "priority": "Baja",
      "project": "Super Tranquilidad iA",
      "account": "Iberdrola",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/30a4f145f5cf80ca990cd44aa774cd06",
      "rating": 1,
      "effort": null
    },
    {
      "id": "3064f145f5cf8076a9ebee9048595cbc",
      "name": "Estatus Creativo (S12)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Direccion Creativa",
      "account": "Ogilvy",
      "date": "17 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3064f145f5cf8076a9ebee9048595cbc",
      "rating": null,
      "effort": null
    },
    {
      "id": "3064f145f5cf80c48462c5e9ce973906",
      "name": "Estatus Creativo (S11)",
      "status": "Pendiente",
      "priority": "Baja",
      "project": "Direccion Creativa",
      "account": "Ogilvy",
      "date": "11 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3064f145f5cf80c48462c5e9ce973906",
      "rating": null,
      "effort": null
    },
    {
      "id": "2c04f145f5cf80d49dc8f1400c610bd7",
      "name": "Best Ads 2025",
      "status": "Pausa",
      "priority": "Sin prioridad",
      "project": "Direccion Creativa",
      "account": "Ogilvy",
      "date": "SIN FECHA",
      "people": [],
      "url": "https://app.notion.com/p/2c04f145f5cf80d49dc8f1400c610bd7",
      "rating": null,
      "effort": null
    },
    {
      "id": "3c64f145f5cf80b98876e98b8f64af5e",
      "name": "Presentacion",
      "status": "En progreso",
      "priority": "Sin prioridad",
      "project": "Ferrero 2026",
      "account": "Banca March",
      "date": "17 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3c64f145f5cf80b98876e98b8f64af5e",
      "rating": null,
      "effort": null
    },
    {
      "id": "3c64f145f5cf8047a97de4cb6a236ed0",
      "name": "Presentacion",
      "status": "Pausa",
      "priority": "Sin prioridad",
      "project": "Proyectos II",
      "account": "Leroy Merlin",
      "date": "23 SEP",
      "people": [],
      "url": "https://app.notion.com/p/3c64f145f5cf8047a97de4cb6a236ed0",
      "rating": null,
      "effort": null
    },
    {
      "id": "3914f145f5cf802fb216d6997650336a",
      "name": "Offline AG",
      "status": "En progreso",
      "priority": "Sin prioridad",
      "project": "GFDLC 26",
      "account": "Leroy Merlin",
      "date": "10 JUL",
      "people": [],
      "url": "https://app.notion.com/p/3914f145f5cf802fb216d6997650336a",
      "rating": null,
      "effort": null
    },
    {
      "id": "3724f145f5cf800b87ead52026d07aeb",
      "name": "Estrategia",
      "status": "Pendiente",
      "priority": "Sin prioridad",
      "project": "GSO 26",
      "account": "ONCE",
      "date": "01 JUN",
      "people": [],
      "url": "https://app.notion.com/p/3724f145f5cf800b87ead52026d07aeb",
      "rating": null,
      "effort": null
    },
    {
      "id": "3194f145f5cf807f9a37c033e9f6e5e6",
      "name": "Loreto Manzanera",
      "status": "Pendiente",
      "priority": "Sin prioridad",
      "project": "Direccion Creativa",
      "account": "Ogilvy",
      "date": "11 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3194f145f5cf807f9a37c033e9f6e5e6",
      "rating": null,
      "effort": null
    },
    {
      "id": "3064f145f5cf80cab345d491699f6c47",
      "name": "Presentacion Transversal",
      "status": "Pendiente",
      "priority": "Sin prioridad",
      "project": "Transversal",
      "account": "ONCE",
      "date": "06 MAR",
      "people": [],
      "url": "https://app.notion.com/p/3064f145f5cf80cab345d491699f6c47",
      "rating": null,
      "effort": null
    }
  ],
  "team": [
    {
      "id": "2b94f145f5cf804faa7ace650c130875",
      "url": "https://app.notion.com/2b94f145f5cf804faa7ace650c130875",
      "name": "Ainhoa Abreu",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "ideas",
        "daily",
        "ia",
        "implicacion"
      ],
      "growth": [
        "presentaciones",
        "diseño",
        "ia"
      ],
      "joined": "2025-07-01",
      "initials": "AA",
      "tone": "pink",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf805a8e4fc3e2d42bd47a",
      "url": "https://app.notion.com/2b94f145f5cf805a8e4fc3e2d42bd47a",
      "name": "Alberto Gómez",
      "role": "Copywriter",
      "assignment": "Equipo",
      "tier": "S",
      "skills": [
        "conceptualizacion",
        "ideas",
        "autonomia",
        "presentaciones",
        "implicacion"
      ],
      "growth": [
        "craft",
        "ia"
      ],
      "joined": "2023-03-01",
      "initials": "AG",
      "tone": "violet",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf805fa077f93901273cd3",
      "url": "https://app.notion.com/2b94f145f5cf805fa077f93901273cd3",
      "name": "Anais Ferrer",
      "role": "Copywriter",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "ideas",
        "redaccion",
        "presentaciones"
      ],
      "growth": [
        "implicacion",
        "ia"
      ],
      "joined": "2016-01-01",
      "initials": "AF",
      "tone": "orange",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf80a3b1e3e1c38504fbbe",
      "url": "https://app.notion.com/2b94f145f5cf80a3b1e3e1c38504fbbe",
      "name": "Elena Torrego",
      "role": "Copywriter",
      "assignment": "Equipo",
      "tier": "C",
      "skills": [
        "volumen",
        "daily",
        "presentaciones"
      ],
      "growth": [
        "craft",
        "ia",
        "ideas",
        "implicacion"
      ],
      "joined": "2004-01-01",
      "initials": "ET",
      "tone": "green",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2e94f145f5cf802b850ded5413c9e9b4",
      "url": "https://app.notion.com/2e94f145f5cf802b850ded5413c9e9b4",
      "name": "Irene Muñoz",
      "role": "Copywriter",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "redaccion",
        "activaciones",
        "presentaciones"
      ],
      "growth": [
        "ideas",
        "volumen"
      ],
      "joined": null,
      "initials": "IM",
      "tone": "blue",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf802a98ccd39e64290579",
      "url": "https://app.notion.com/2b94f145f5cf802a98ccd39e64290579",
      "name": "Izarbe Moreno",
      "role": "Copywriter",
      "assignment": "Extra",
      "tier": "A",
      "skills": [
        "ideas",
        "craft",
        "redaccion",
        "presentaciones",
        "autonomia"
      ],
      "growth": [],
      "joined": "2024-07-01",
      "initials": "IM",
      "tone": "yellow",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf80c49f66ff87aa9a8568",
      "url": "https://app.notion.com/2b94f145f5cf80c49f66ff87aa9a8568",
      "name": "Iñaki Garrido",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "S",
      "skills": [
        "volumen",
        "ideas",
        "autonomia",
        "ia"
      ],
      "growth": [
        "craft",
        "presentaciones",
        "diseño"
      ],
      "joined": "2023-03-01",
      "initials": "IG",
      "tone": "cyan",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf80629ed0e548f9a1f955",
      "url": "https://app.notion.com/2b94f145f5cf80629ed0e548f9a1f955",
      "name": "Jorge Calvo",
      "role": "Director Creativo",
      "assignment": "Equipo",
      "tier": null,
      "skills": [],
      "growth": [],
      "joined": "2016-05-01",
      "initials": "JC",
      "tone": "red",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf808f9d8efed361ae148f",
      "url": "https://app.notion.com/2b94f145f5cf808f9d8efed361ae148f",
      "name": "Jose Garcinuño",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "X",
      "skills": [
        "daily"
      ],
      "growth": [
        "craft",
        "diseño",
        "presentaciones",
        "ideas",
        "conceptualizacion",
        "implicacion",
        "ia"
      ],
      "joined": "2003-01-01",
      "initials": "JG",
      "tone": "pink",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf805aa22adbce3a99c871",
      "url": "https://app.notion.com/2b94f145f5cf805aa22adbce3a99c871",
      "name": "Joseba y Galindo",
      "role": "Freelance",
      "assignment": "Freelance",
      "tier": "A",
      "skills": [
        "ideas"
      ],
      "growth": [],
      "joined": null,
      "initials": "JY",
      "tone": "violet",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "3584f145f5cf8026981bfef3e45a830d",
      "url": "https://app.notion.com/3584f145f5cf8026981bfef3e45a830d",
      "name": "Lucero Soria",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "S",
      "skills": [
        "ideas",
        "conceptualizacion",
        "diseño",
        "presentaciones",
        "ia",
        "craft"
      ],
      "growth": [],
      "joined": "2026-08-03",
      "initials": "LS",
      "tone": "orange",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf8062a505fac0d8088673",
      "url": "https://app.notion.com/2b94f145f5cf8062a505fac0d8088673",
      "name": "Lucho Martín",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "A",
      "skills": [
        "volumen",
        "diseño",
        "ia",
        "implicacion",
        "autonomia"
      ],
      "growth": [
        "ideas",
        "conceptualizacion"
      ],
      "joined": "2025-04-01",
      "initials": "LM",
      "tone": "green",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf80f586b1f7e5bdd43384",
      "url": "https://app.notion.com/2b94f145f5cf80f586b1f7e5bdd43384",
      "name": "Lucía Moreno",
      "role": "Director de Arte",
      "assignment": "Extra",
      "tier": "S",
      "skills": [
        "conceptualizacion",
        "ideas",
        "autonomia",
        "craft",
        "ia",
        "diseño",
        "presentaciones"
      ],
      "growth": [],
      "joined": "2023-06-01",
      "initials": "LM",
      "tone": "blue",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf801dabd7dee6b5d6c9d8",
      "url": "https://app.notion.com/2b94f145f5cf801dabd7dee6b5d6c9d8",
      "name": "Marta Galán",
      "role": "Copywriter",
      "assignment": "Extra",
      "tier": "S",
      "skills": [
        "ideas",
        "craft",
        "ia",
        "redaccion",
        "presentaciones",
        "conceptualizacion"
      ],
      "growth": [],
      "joined": "2023-06-01",
      "initials": "MG",
      "tone": "yellow",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf8086bb22f34df267b2ac",
      "url": "https://app.notion.com/2b94f145f5cf8086bb22f34df267b2ac",
      "name": "Marta Rumbo",
      "role": "Copywriter",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "ideas",
        "daily",
        "implicacion"
      ],
      "growth": [
        "conceptualizacion",
        "craft",
        "ia",
        "presentaciones"
      ],
      "joined": "2025-07-01",
      "initials": "MR",
      "tone": "cyan",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf80189655ca8f82e1eb50",
      "url": "https://app.notion.com/2b94f145f5cf80189655ca8f82e1eb50",
      "name": "Myriam Cuervo",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "volumen",
        "diseño",
        "implicacion"
      ],
      "growth": [
        "ideas",
        "craft"
      ],
      "joined": "2025-11-14",
      "initials": "MC",
      "tone": "red",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf802abe63d0f582c398aa",
      "url": "https://app.notion.com/2b94f145f5cf802abe63d0f582c398aa",
      "name": "Pablo Piqueras",
      "role": "Director de Arte",
      "assignment": "Extra",
      "tier": "A",
      "skills": [
        "ideas",
        "craft",
        "diseño",
        "ia",
        "autonomia",
        "presentaciones"
      ],
      "growth": [],
      "joined": "2024-07-01",
      "initials": "PP",
      "tone": "pink",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "3584f145f5cf8017bd89de02338e8b54",
      "url": "https://app.notion.com/3584f145f5cf8017bd89de02338e8b54",
      "name": "Paulina Lavín",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "B",
      "skills": [
        "diseño",
        "daily",
        "autonomia"
      ],
      "growth": [
        "craft",
        "ideas",
        "conceptualizacion",
        "presentaciones"
      ],
      "joined": "2026-06-01",
      "initials": "PL",
      "tone": "violet",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf805a8c56ef50c69c2090",
      "url": "https://app.notion.com/2b94f145f5cf805a8c56ef50c69c2090",
      "name": "Ramiro Alda",
      "role": "Director Creativo",
      "assignment": "Equipo",
      "tier": null,
      "skills": [],
      "growth": [],
      "joined": "2004-01-01",
      "initials": "RA",
      "tone": "orange",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    },
    {
      "id": "2b94f145f5cf806598eee54190bfbdbb",
      "url": "https://app.notion.com/2b94f145f5cf806598eee54190bfbdbb",
      "name": "Santiago Fiz",
      "role": "Director de Arte",
      "assignment": "Equipo",
      "tier": "A",
      "skills": [
        "ideas",
        "ia",
        "daily",
        "diseño",
        "autonomia",
        "presentaciones",
        "activaciones"
      ],
      "growth": [],
      "joined": "2025-04-01",
      "initials": "SF",
      "tone": "green",
      "load": 0,
      "activeTasks": 0,
      "activeProjects": 0,
      "completedTasks": 0,
      "completedProjects": 0,
      "score": null,
      "taskScore": null,
      "projectScore": null,
      "evaluations": 0,
      "ratio": null,
      "distribution": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0
      },
      "dimensions": {
        "quality": null,
        "timing": null,
        "collaboration": null,
        "autonomy": null,
        "impact": null
      }
    }
  ],
  "holidays": [
    {
      "name": "Myriam Cuervo",
      "type": "Libres",
      "start": "2026-09-07",
      "end": "2026-09-15",
      "label": "07 SEP — 15 SEP",
      "color": "#70d6ff",
      "url": "https://app.notion.com/p/3114f145f5cf808b8918edb0e7a4d679"
    },
    {
      "name": "Santiago Fiz",
      "type": "Libres",
      "start": "2026-10-07",
      "end": "2026-10-14",
      "label": "07 OCT — 14 OCT",
      "color": "#ff9f43",
      "url": "https://app.notion.com/p/3bb4f145f5cf8091b411e3240b847d7f"
    },
    {
      "name": "Alberto Gómez",
      "type": "Libres",
      "start": "2026-08-17",
      "end": "2026-09-04",
      "label": "17 AGO — 04 SEP",
      "color": "#ef8ea0",
      "url": "https://app.notion.com/p/38b4f145f5cf8025b79fc2d1a863ee44"
    }
  ]
} as const;

